---
abstract: 'A Perl interface to the F5 iControl API'
author:
  - 'Luke Poskitt <ltp@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: BigIP-iControl
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  MIME::Base64: 0
  SOAP::Lite: 0
  Test::More: 0
version: 0.07
